// Generated by CoffeeScript 1.6.1
(function() {
  var data_collection, mongo, request, _;

  request = require('request');

  _ = require('underscore');

  mongo = require('mongodb').MongoClient;

  data_collection = null;

  mongo.connect('mongodb://localhost:27017/doubanfm', function(err, db) {
    if (!err) {
      console.log('Connected to mongodb');
      return data_collection = db.collection('data');
    } else {
      return console.log('Error connecting mongodb');
    }
  });

  exports.index = function(req, res) {
    return res.render('index', {
      title: 'hello'
    });
  };

  exports.collect = function(req, res) {
    var data;
    data = JSON.parse(req.body.data);
    return request('https://api.douban.com/v2/user/' + data.id, function(error, response, body) {
      var user_info;
      user_info = JSON.parse(body);
      if (user_info.code) {
        return res.json({
          error: 1,
          msg: 'can not fetch user info'
        });
      }
      _.extend(data, user_info);
      data.url = data.alt;
      delete data.alt;
      console.log(data);
      return data_collection.insert(data, {
        w: 1
      }, function(err, result) {
        if (err) {
          return res.json({
            error: 1,
            msg: 'can not insert data to mongodb'
          });
        }
        return res.json({
          uid: user_info.uid
        });
      });
    });
  };

  exports.show = function(req, res) {
    var uid;
    uid = req.params.uid;
    return data_collection.findOne({
      uid: uid
    }, function(err, item) {
      if (err) {
        return res.json({
          error: 1,
          msg: 'error find user'
        });
      }
      return res.json(item);
    });
  };

}).call(this);
