// Generated by CoffeeScript 1.6.1
(function() {
  var douban, jobs, kue, mongo, mongodb, raw_data_collection, request, _;

  request = require('request');

  mongodb = require('mongodb');

  _ = require('underscore');

  kue = require('kue');

  douban = require('../lib/douban');

  jobs = kue.createQueue();

  mongo = mongodb.MongoClient;

  raw_data_collection = null;

  mongo.connect('mongodb://localhost:27017/doubanfm', function(err, db) {
    if (!err) {
      console.log('Connected to mongodb');
      return raw_data_collection = db.collection('raw_data');
    } else {
      return console.log('Error connecting mongodb');
    }
  });

  exports.index = function(req, res) {
    return res.render('index', {
      title: 'hello'
    });
  };

  exports.collect = function(req, res) {
    var data;
    data = JSON.parse(req.body.data);
    return douban.user_info(data.id, function(error, user_info) {
      console.log(user_info);
      if (error) {
        return res.json({
          error: 1,
          msg: 'can not fetch user info'
        });
      }
      _.extend(data, user_info);
      return raw_data_collection.update({
        id: data.id
      }, data, {
        w: 1,
        upsert: true
      }, function(err, result) {
        var job;
        if (err) {
          return res.json({
            error: 1,
            msg: 'can not insert data to mongodb'
          });
        }
        job = jobs.create('stats', {
          title: data.uid,
          id: data.id
        });
        job.attempts(5).save();
        return res.json({
          uid: data.uid
        });
      });
    });
  };

  exports.show = function(req, res) {
    var uid;
    uid = req.params.uid;
    return raw_data_collection.findOne({
      uid: uid
    }, function(err, item) {
      if (err) {
        return res.json({
          error: 1,
          msg: 'error find user'
        });
      }
      return res.json(item);
    });
  };

}).call(this);
