// Generated by CoffeeScript 1.6.1
(function() {
  var async, connectMongo, get_tags, mongo, mongodb, music, process, raw_data_collection, stats_collection, _;

  mongodb = require('mongodb');

  async = require('async');

  _ = require('underscore');

  music = require('./music');

  mongo = mongodb.MongoClient;

  stats_collection = raw_data_collection = null;

  connectMongo = function(callback) {
    return mongo.connect('mongodb://localhost:27017/doubanfm', function(err, db) {
      if (!err) {
        console.log('stats connected to mongodb');
        raw_data_collection = db.collection('raw_data');
        stats_collection = db.collection('stats_data');
        return callback();
      } else {
        return console.log('Error connecting mongodb');
      }
    });
  };

  exports.process = function(job, done) {
    if (!raw_data_collection) {
      return connectMongo(function() {
        return process(job, done);
      });
    } else {
      return process(job, done);
    }
  };

  get_tags = function(album_ids, callback) {
    return async.map(album_ids, music.tags, function(err, results) {
      var result, tag, tag_title, tags, _i, _j, _len, _len1, _ref;
      tags = {};
      for (_i = 0, _len = results.length; _i < _len; _i++) {
        result = results[_i];
        console.log(result);
        _ref = result.tags;
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          tag = _ref[_j];
          tag_title = tag.title;
          if (!(tag_title in tags)) {
            tags[tag_title] = 0;
          }
          tags[tag_title] += tag.count;
        }
      }
      return callback(null, tags);
    });
  };

  process = function(job, done) {
    console.log(job.data);
    return raw_data_collection.findOne({
      id: job.data.id
    }, function(err, item) {
      var album_ids;
      job.log('processing %s(%s), who has %s liked songs', item.uid, item.id, item.liked_song_count);
      album_ids = _.pluck(item.songs, 'album_id');
      return get_tags(album_ids, function(error, tags) {
        console.log(tags);
        return done();
      });
    });
  };

}).call(this);
