// Generated by CoffeeScript 1.6.1
(function() {
  var async, connectMongo, douban, get_tags, mongo, mongodb, process, raw_data_collection, stats_collection, _;

  mongodb = require('mongodb');

  async = require('async');

  _ = require('underscore');

  douban = require('../lib/douban');

  mongo = mongodb.MongoClient;

  stats_collection = raw_data_collection = null;

  connectMongo = function(callback) {
    return mongo.connect('mongodb://localhost:27017/doubanfm', function(err, db) {
      if (!err) {
        console.log('stats connected to mongodb');
        raw_data_collection = db.collection('raw_data');
        stats_collection = db.collection('stats_data');
        return callback();
      } else {
        return console.log('Error connecting mongodb');
      }
    });
  };

  exports.process = function(job, done) {
    if (!raw_data_collection) {
      return connectMongo(function() {
        return process(job, done);
      });
    } else {
      return process(job, done);
    }
  };

  get_tags = function(album_ids, callback) {
    var parallel_req_limit;
    parallel_req_limit = 5;
    return async.mapLimit(album_ids, parallel_req_limit, douban.music_tags, function(err, results) {
      var count, result, tag, tags, _i, _j, _len, _len1;
      tags = {};
      for (_i = 0, _len = results.length; _i < _len; _i++) {
        result = results[_i];
        for (_j = 0, _len1 = result.length; _j < _len1; _j++) {
          tag = result[_j];
          tags[tag] = (tags[tag] || 0) + 1;
        }
      }
      for (tag in tags) {
        count = tags[tag];
        if (count <= 1) {
          delete tags[tag];
        }
      }
      return callback(null, tags);
    });
  };

  process = function(job, done) {
    console.log(job.data);
    return raw_data_collection.findOne({
      id: job.data.id
    }, function(err, item) {
      var album_ids;
      job.log('processing %s(%s), who has %s liked songs', item.uid, item.id, item.liked_song_count);
      album_ids = _.compact(_.pluck(item.songs, 'album_id'));
      return get_tags(album_ids, function(error, tags) {
        console.log(tags);
        return done();
      });
    });
  };

}).call(this);
