// Generated by CoffeeScript 1.6.1
(function() {
  var connectMongo, mongo, process, raw_data_collection, stats_collection;

  mongo = require('mongodb').MongoClient;

  stats_collection = raw_data_collection = null;

  connectMongo = function(callback) {
    return mongo.connect('mongodb://localhost:27017/doubanfm', function(err, db) {
      if (!err) {
        console.log('stats connected to mongodb');
        raw_data_collection = db.collection('raw_data');
        stats_collection = db.collection('stats_data');
        return callback();
      } else {
        return console.log('Error connecting mongodb');
      }
    });
  };

  exports.process = function(job, done) {
    if (!raw_data_collection) {
      return connectMongo(function() {
        return process(job, done);
      });
    } else {
      return process(job, done);
    }
  };

  process = function(job, done) {
    console.log(job.data);
    return raw_data_collection.findOne({
      id: job.data.id
    }, function(err, item) {
      job.log('processing %s(%s), who has %s liked songs', item.uid, item.id, item.liked_song_count);
      return setTimeout(done, 10 * 1000);
    });
  };

}).call(this);
